### ISSUE TITLE
How to set locale globally?

### ISSUE THREAD

**Issue by th1agoms** [nuxt-community/date-fns-module#13]
Sorry, this is my first time using Date-fns and I don't understand how to set locale global (in modules). I've tried the following from one of the older issues, but I get the error 'languages is undefined':

`modules: [[
      '@nuxtjs/date-fns',
      {
        locales: languages.map(lang => lang.locale),
        defaultLocale: 'pt',
        format: 'DD/MM/YYYY'
      }
    ]]`

Could you please help me or improve the documentation a little for newcomers like me?

Thank you very much for the amazing lib!

**Comment by ricardogobbosouza** [comment]
Hi @th1agoms, its simple:

```js
// nuxt.config.js
{
  modules: [
    '@nuxtjs/date-fns'
  ],

  dateFns: {
    defaultLocale: 'pt'
  }
}
```
