### ISSUE TITLE
ERROR in ./.nuxt/date-fns.js

### ISSUE THREAD

**Issue by desiboli** [nuxt-community/date-fns-module#17]
Hi! after upgrading to version 1.0.0 I get this error in Nuxt build.

```
ERROR in ./.nuxt/date-fns.js
Module not found: Error: Can't resolve 'date-fns/locale' in '.nuxt'
 @ ./.nuxt/date-fns.js 14:0-37 61:18-20
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error
```

Nuxt version: 2.10.0

**Comment by ricardogobbosouza** [comment]
@desiboli Try re-install dependencies:
`rm -rf node_modules yarn.lock && yarn`

**Comment by Diglio** [comment]
Getting the same error on a fresh install of this package on a fresh nuxt project.

**Comment by ricardogobbosouza** [comment]
@Diglio Please provide a repository and step by step to reproduce

**Comment by ricardogobbosouza** [comment]
It works for me.

**Comment by ricardogobbosouza** [comment]
It works for me.
Try this:

```html
<template>
    <div>
        {{ $dateFns.format(new Date()) }}
    </div>
</template>
```
```json
// package.json
{
  "private": true,
  "scripts": {
    "dev": "nuxt"
  },
  "dependencies": {
    "nuxt": "^2.10.0"
  },
  "devDependencies": {
    "@nuxtjs/date-fns": "^1.0.0"
  }
}
```
```js
// nuxt.config.js
export default {
  buildModules: [
    '@nuxtjs/date-fns'
  ],
  dateFns: {
    format: 'yyyy-MM-dd'
  }
}
```

**Comment by desiboli** [comment]
Ok I was trying to reproduce this issue in a fresh Nuxtjs project using Nuxt cli (npx).
I created an SPA app and stumbled into another issue that blocked me from reproducing this reported issue with date-fns/locale.

This is the issue https://github.com/nuxt/nuxt.js/issues/6500

You can reproduce this issue in this repo: https://github.com/desiboli/nuxt-error

**NOTE:** that I'm using NPM not Yarn!

In my current project I still couldn't fix the error, I did the following steps:
1. Deletet node_modules
2. Added `buildModules: [
    '@nuxtjs/date-fns'
  ],
  dateFns: {
    format: 'yyyy-MM-dd'
  }` and removed the module from 
`modules: [
  ]`

3. I also moved the package from dependencies to devDependencies.
4. npm install
5. npm run build
6. Same error! :-(

**Comment by ricardogobbosouza** [comment]
@desiboli It's a problem with nuxt v2.10.0

**Comment by 6ones** [comment]
Installing [date-fns](https://date-fns.org/docs/Getting-Started#installation) solves the issue.

The generated files from the build depend on date-fns.

**Comment by ricardogobbosouza** [comment]
@desiboli update nuxt to v2.10.1

Does this still occur?

**Comment by desiboli** [comment]
@ricardogobbosouza yes unfortunately this still occurs!
I have still not tested @6ones solution by installing the date-fns package, but it should not be necessary right ?

So I did the following before trying out the "npm run build" again where the issue occurs.

1. Removed node_modules
2. Removed package-lock.json file
3. npm cache clean
4. npm install
5. npm run build
6. Error: ```
ERROR in ./.nuxt/date-fns.js
Module not found: Error: Can't resolve 'date-fns/locale' in '/Users/musse/Sites/plucktv/.nuxt'
```

Nuxt version: "nuxt": "2.10.1",
Nuxt/date-fns version: "@nuxtjs/date-fns": "1.0.0", 
Nuxt.config.js settings:
```
mode: 'spa'
  modules: [
    '@nuxtjs/pwa',
    '@nuxtjs/axios',
    '@nuxtjs/style-resources',
    '@nuxtjs/bulma',
    'nuxt-device-detect'
  ],
  styleResources: {
    scss: [
      '~assets/scss/styles.scss'
    ]
  },
  buildModules: [
    ['@nuxtjs/date-fns']
  ],
  dateFns: {
    locales: ['sv'],
    defaultLocale: 'sv',
    format: 'yyyy-MM-dd'
  },
```

**Comment by ricardogobbosouza** [comment]
@desiboli I still can't reproduce this issue
Please check the version of `date-fns`

**Comment by ricardogobbosouza** [comment]
If the problem persists, please reopen

**Comment by pancake-boy** [comment]
still an issue on a fresh install

**Comment by ricardogobbosouza** [comment]
@desiboli , @pancake-boy 
I still can't reproduce this issue
Please provide a repository to reproduce

**Comment by mikehoh** [comment]
Probably you have installed `date-fns` globally that's why you don't see this error.

As said @6ones `Installing date-fns solves the issue.`
Just `npm install date-fns --save` and it'll work.
