### ISSUE TITLE
Typing for $dateFns

### ISSUE THREAD

**Issue by warheartvik** [nuxt-community/date-fns-module#2]
Hello,

I'm using date-fns, and It works fine, but I think i'm missing the typing for $dateFns in Typescript.

![image](https://user-images.githubusercontent.com/43218752/57953422-a12ceb00-78b5-11e9-9172-cf3c1dc5d684.png)

I made it work using //@ts-ignore

![image](https://user-images.githubusercontent.com/43218752/57953486-ca4d7b80-78b5-11e9-8194-a81a21893671.png)

But I'd like to know how to prevent this behavior. Maybe $dateFns in not avaible to be used this way? How can I made it avaible for this use? 

Please advise!

**Comment by ricardogobbosouza** [comment]
Hi @warheartvik $dateFns not have typing still
