### ISSUE TITLE
[Vue warn]: Property or method "$dateFns" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by mtltechtemp** [nuxt-community/date-fns-module#3]
I believe this is an issue related to SSR.
Any workaround?

csb: https://codesandbox.io/embed/codesandboxnuxt-n4kmq

**Comment by mtltechtemp** [comment]
Ping @ricardogobbosouza

**Comment by ricardogobbosouza** [comment]
Hi @mtltechtemp 
I could not reproduce

**Comment by ricardogobbosouza** [comment]
Hi @mtltechtemp 
Resolved on version `0.1.1`

**Comment by ricardogobbosouza** [comment]
In version `0.1.1` added types for typescript
Do not forget to add it in `tsconfig.json`

```js
{
  "compilerOptions": {
    ...,
    "types": [
      ...,
      "@nuxtjs/date-fns"
    ]
  }
}
```

**Comment by roselily8** [comment]
I've added the type to tsconfig but the error persists.
