### ISSUE TITLE
Why this module?

### ISSUE THREAD

**Issue by NickBolles** [nuxt-community/date-fns-module#33]
I'm looking to add date-fns to my app, and I ran across this, but I'm struggling to see why this module would be needed and why we can't just import date-fns, especially with composition-api.

Could someone fill me in on why a module is better than just importing it? maybe adding something to the readme would be helpful too.

**Comment by ricardogobbosouza** [comment]
Hi @NickBolles 
This module is used to configure `date-fns` more easily, being able to configure it in `nuxt.config.js`

**Comment by ricardogobbosouza** [comment]
A suggested description is always welcome :smile:

**Comment by NickBolles** [comment]
Gotcha, so it's mostly just for configuration around it. Thank you!
