### ISSUE TITLE
Spanish locale not working?

### ISSUE THREAD

**Issue by cecurin** [nuxt-community/date-fns-module#34]
Hi there! I tried to make this module work in Spanish but I couldn't. Is there a problem with locales? or Nuxt? or is my code?

Here's my code:
```
module.exports = {
  mode: 'universal',
  buildModules: [
    '@nuxtjs/date-fns',
    ...
  ],
  dateFns: {
    locales: ['es'],
    defaultLocale: 'es',
    format: 'dd-MM-yyyy'
  },
```

And my implementation is this:
```
function parseDateAgo (value) {
  // value = date from server
  // e.g: 2020-05-22T03:42:40.740604Z

  if (!value) { return null }

  return formatDistanceToNow(parseISO(value), { addSuffix: true })
}
```

And 
```
<div class="text-muted">
  ...
  <p>
    Termina
    {{ parseDateAgo(post.finish_date) }}
  </p>
  ...
</div>
```
Finally it prints: "Termina 4 days ago", when it had to be in Spanish: "Termina en 4 días más". So, what am I doing wrong?

Thanks in advance

**Comment by hmaesta** [comment]
Try adding `locale: 'es'` to `formatDistanceToNow` options.

```js
return formatDistanceToNow(parseISO(value), { addSuffix: true, locale: 'es' })
```

**Comment by ricardogobbosouza** [comment]
Hi @cecurin 
Use `$dateFns` object, it will automatically merge your default settings

```js
$dateFns.formatDistanceToNow($dateFns.parseISO(value), { addSuffix: true })
```

**Comment by cecurin** [comment]
> 
> 
> Try adding `locale: 'es'` to `formatDistanceToNow` options.
> 
> ```js
> return formatDistanceToNow(parseISO(value), { addSuffix: true, locale: 'es' })
> ```

This worked for me. I'm calling the function outside Vue scope, in a plugin.

Inside the templates this worked:
> 
> 
> Hi @cecurin
> Use `$dateFns` object, it will automatically merge your default settings
> 
> ```js
> $dateFns.formatDistanceToNow($dateFns.parseISO(value), { addSuffix: true })
> ```
