### ISSUE TITLE
formatDuration not being localized

### ISSUE THREAD

**Issue by codesxt** [nuxt-community/date-fns-module#37]
I'm working with several dates in Spanish with the 'es' locale. Most of them are working fine, like 'formatDistanceToNow' which gives me the date distance in proper Spanish. But when I call 'formatDuration' it gives me the result in English.

When I force the locale using `$dateFns.formatDuration(duration, { locale: 'es' })` it gives me the following rendering error:

```
locale.formatDistance is not a function`
```

I'm using:

- nuxtjs/date-fns version 1.3.1

Locale objects are being properly loaded from date-fns so the problem must be in this plugin.

**Comment by codesxt** [comment]
I just realized that the error is solved by adding `'formatDuration'` to the twoParams array in the file `@nuxtjs/date-fns/lib/plugin.js`.

I'll add a PR to add that.

**Comment by ricardogobbosouza** [comment]
Thanks @codesxt

**Comment by codesxt** [comment]
@ricardogobbosouza Will this be in a new version soon? Just to know.

**Comment by ricardogobbosouza** [comment]
@codesxt release v1.4.0
