### ISSUE TITLE
[date-fns] locale 'en' not found.

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/date-fns-module#41]
nuxt.config.js:

```js
  dateFns: {
    locales: ['ru', 'en', 'kk'],
    defaultLocale: 'ru',
  },
```

component.vue:

```js

<div>{{
  $dateFns.format(n.created_at, 'dd MMMM, yyyy, HH:mm', {
    locale: 'en',
  })
}}</div>
```

Throws me an error: "[date-fns] locale 'en' not found." If i choose other languages, like 'ru', 'kk' - it does work, issue is with en language.

**Comment by ricardogobbosouza** [comment]
Hi @webcoderkz 

Try to use `en-US`.
See https://date-fns.org/v2.16.1/docs/Locale
