### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by gilles6** [nuxt-community/date-fns-module#44]
After installing and configuring `date-fns` module as per the documentation, I'm getting the following error:
```
TypeError: Cannot read property 'map' of null
    at Module.format
```
How can I fix it ?

**Comment by ricardogobbosouza** [comment]
Hi @gilles6 
Can you share part of your configuration?

**Comment by 4Kazelot** [comment]
@gilles6 
I had the same error. Your config cannot be empty. It should look like this:
```
dateFns: {
        locales: ['es', 'ru', 'pt-BR'],
        defaultLocale: 'en-US',
        format: 'yyyy-MM-dd'
    },
```
